apiVersion: v1
kind: Service
metadata:
  namespace: caas-system
  name: jiange
  labels:
    app: jiange
spec:
  ports:
  - port: 443
    targetPort: 443
    name: https-jiange
  selector:
    app: jiange
