name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  S3uploads:
    runs-on: daas-runner
    strategy:
      matrix:
        go-version: ["1.17"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Lint
        run: go vet ./...
      - name: Test
        run: go test ./...
